### PR TITLE
Upgrade project to Meteor 1.3

### PR DESCRIPTION
**Pull request by darko-mijic**

### CODE REVIEW

**Comment by darko-mijic** [comment]
I need WIP (work in progress) label here. Can you create it on this project @AndyatFocallocal? And on streetsleeper too. If so make it yellow please.

**Comment by darko-mijic** [comment]
We have a temporary hack here `client/compatibility/prunecluster_prunecluster.js". I can see that similar hacks where used previously so I took the same approach. There are much more important things to do now that we can run this on Meteor 1.3.

**Comment by darko-mijic** [comment]
The hack is related to usage of `https://atmospherejs.com/prunecluster/prunecluster` package.

**Comment by distalx** [comment]
seems legit, merging it.

**Pull request merged**
